export { HomePage } from './HomePage'
export { CollectionPage } from './CollectionPage'
export { ProductPage } from './ProductPage'
export { AboutPage } from './AboutPage'
export { SearchPage } from './SearchPage'
export { PrivacyPolicyPage } from './PrivacyPolicyPage'
export { TermsAndConditionsPage } from './TermsAndConditionsPage'
